// This file is generated by tooling/generate-bindings.mjs.
// Source: packages/contracts/out/*/*.json; do not edit by hand.

export const PayGuardActionRouterAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registry_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "vault_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "DECISION_ALLOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DECISION_DENY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancel",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createRequest",
    "inputs": [
      {
        "name": "input",
        "type": "tuple",
        "internalType": "struct PayGuardTypes.ActionRequest",
        "components": [
          {
            "name": "chainId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "registry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "policyId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "policyVersion",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "policyCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "requestId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "requestNonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "attempt",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "requester",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "target",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "actionType",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "scheduleSlot",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "occurrence",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "spendCheckpoint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "balanceCheckpoint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "inputCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "graceDeadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "digestCounts",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "count",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "evaluationAttestationDigest",
    "inputs": [
      {
        "name": "result",
        "type": "tuple",
        "internalType": "struct PayGuardTypes.EvaluationResult",
        "components": [
          {
            "name": "request",
            "type": "tuple",
            "internalType": "struct PayGuardTypes.ActionRequest",
            "components": [
              {
                "name": "chainId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "registry",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "vault",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "router",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "policyId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "policyVersion",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "policyCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "requestId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "requestNonce",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "attempt",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "requester",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "target",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "asset",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "actionType",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "amount",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "scheduleSlot",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "occurrence",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "spendCheckpoint",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "balanceCheckpoint",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "inputCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "createdAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "graceDeadline",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "expiry",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "decision",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "publicReasonClass",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "reservedAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "resultingCheckpoint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "resultNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "attempt",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "issuedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "machineId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "keyFingerprint",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "evaluationDigest",
    "inputs": [
      {
        "name": "result",
        "type": "tuple",
        "internalType": "struct PayGuardTypes.EvaluationResult",
        "components": [
          {
            "name": "request",
            "type": "tuple",
            "internalType": "struct PayGuardTypes.ActionRequest",
            "components": [
              {
                "name": "chainId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "registry",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "vault",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "router",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "policyId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "policyVersion",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "policyCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "requestId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "requestNonce",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "attempt",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "requester",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "target",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "asset",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "actionType",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "amount",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "scheduleSlot",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "occurrence",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "spendCheckpoint",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "balanceCheckpoint",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "inputCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "createdAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "graceDeadline",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "expiry",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "decision",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "publicReasonClass",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "reservedAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "resultingCheckpoint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "resultNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "attempt",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "issuedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "machineId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "keyFingerprint",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "execute",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "expire",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getRequest",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PayGuardActionRouter.StoredRequest",
        "components": [
          {
            "name": "request",
            "type": "tuple",
            "internalType": "struct PayGuardTypes.ActionRequest",
            "components": [
              {
                "name": "chainId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "registry",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "vault",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "router",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "policyId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "policyVersion",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "policyCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "requestId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "requestNonce",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "attempt",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "requester",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "target",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "asset",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "actionType",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "amount",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "scheduleSlot",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "occurrence",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "spendCheckpoint",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "balanceCheckpoint",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "inputCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "createdAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "graceDeadline",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "expiry",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PayGuardActionRouter.RequestStatus"
          },
          {
            "name": "requestHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "approvedDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "matchingCount",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "approvedDecision",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "approvedReason",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "approvedAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "approvedCheckpoint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "approvedNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "approvedAttempt",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "approvedIssuedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "approvedExpiry",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "machineSubmitted",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "machineId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "submitted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nonceUsed",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "requestNonce",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "used",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract PayGuardPolicyRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "requestHash",
    "inputs": [
      {
        "name": "request",
        "type": "tuple",
        "internalType": "struct PayGuardTypes.ActionRequest",
        "components": [
          {
            "name": "chainId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "registry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "policyId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "policyVersion",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "policyCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "requestId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "requestNonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "attempt",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "requester",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "target",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "actionType",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "scheduleSlot",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "occurrence",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "spendCheckpoint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "balanceCheckpoint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "inputCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "graceDeadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "spendState",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "checkpoint",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "occurrence",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "accountedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "initialized",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitEvaluation",
    "inputs": [
      {
        "name": "input",
        "type": "tuple",
        "internalType": "struct PayGuardTypes.EvaluationResult",
        "components": [
          {
            "name": "request",
            "type": "tuple",
            "internalType": "struct PayGuardTypes.ActionRequest",
            "components": [
              {
                "name": "chainId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "registry",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "vault",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "router",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "policyId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "policyVersion",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "policyCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "requestId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "requestNonce",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "attempt",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "requester",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "target",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "asset",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "actionType",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "amount",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "scheduleSlot",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "occurrence",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "spendCheckpoint",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "balanceCheckpoint",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "inputCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "createdAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "graceDeadline",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "expiry",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "decision",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "publicReasonClass",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "reservedAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "resultingCheckpoint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "resultNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "attempt",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "issuedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "machineId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "keyFingerprint",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "vault",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract PayGuardVault"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "EvaluationAccepted",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "machineId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "decision",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RequestCancelled",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RequestCreated",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "requester",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RequestDenied",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RequestExecuted",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "target",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "checkpoint",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RequestExpired",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ThresholdReached",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "decision",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "DuplicateMachine",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Expired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidEvaluation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRequest",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidState",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NonceAlreadyUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAuthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PolicyStopped",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PolicyUnavailable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RequestAlreadyExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RequesterMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ThresholdUnavailable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownRequest",
    "inputs": []
  }
] as const;

export const PayGuardFoundationSenderAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "extensionRegistry",
        "type": "address",
        "internalType": "contract ITeeExtensionRegistry"
      },
      {
        "name": "machineRegistry",
        "type": "address",
        "internalType": "contract ITeeMachineRegistry"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CODE_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "COSTON2_CHAIN_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "FOUNDATION_DOMAIN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "FOUNDATION_SCHEMA_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "FOUNDATION_SENDER_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "OP_COMMAND",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "OP_TYPE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "foundationBindingHash",
    "inputs": [
      {
        "name": "request",
        "type": "tuple",
        "internalType": "struct PayGuardFoundationSender.FoundationRequest",
        "components": [
          {
            "name": "schemaVersion",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "chainId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sender",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "extensionId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "codeVersion",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "requestNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "payloadHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getExtensionId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sendFoundationPing",
    "inputs": [
      {
        "name": "requestNonce",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "instructionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "setExtensionIdExplicit",
    "inputs": [
      {
        "name": "candidate",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "teeExtensionRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ITeeExtensionRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "teeMachineRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ITeeMachineRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ExtensionIdConfigured",
    "inputs": [
      {
        "name": "extensionId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FoundationPingDispatched",
    "inputs": [
      {
        "name": "instructionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "requestNonce",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "bindingHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "teeId",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "ExtensionIdAlreadySet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExtensionId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidInstructionId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRegistry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRequest",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoTeeSelected",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongChain",
    "inputs": []
  }
] as const;

export const PayGuardPolicyRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "admin_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "STATUS_ACTIVE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STATUS_NONE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STATUS_REVOKED",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STATUS_STOPPED",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPolicy",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "binding",
        "type": "tuple",
        "internalType": "struct PayGuardTypes.PolicyBinding",
        "components": [
          {
            "name": "chainId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "registry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "policyId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "policyVersion",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "policyCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "schema",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "extensionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "codeVersion",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "machineIds",
            "type": "bytes32[3]",
            "internalType": "bytes32[3]"
          },
          {
            "name": "keyFingerprints",
            "type": "bytes32[3]",
            "internalType": "bytes32[3]"
          },
          {
            "name": "custodyThreshold",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "resultThreshold",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "policyNonce",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isFrozenSigner",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "machineId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "keyFingerprint",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "machine",
    "inputs": [
      {
        "name": "machineId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "keyFingerprint",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "registered",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "policyStatus",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerMachine",
    "inputs": [
      {
        "name": "machineId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "keyFingerprint",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registerPolicy",
    "inputs": [
      {
        "name": "binding",
        "type": "tuple",
        "internalType": "struct PayGuardTypes.PolicyBinding",
        "components": [
          {
            "name": "chainId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "registry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "vault",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "policyId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "policyVersion",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "policyCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "schema",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "extensionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "codeVersion",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "machineIds",
            "type": "bytes32[3]",
            "internalType": "bytes32[3]"
          },
          {
            "name": "keyFingerprints",
            "type": "bytes32[3]",
            "internalType": "bytes32[3]"
          },
          {
            "name": "custodyThreshold",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "resultThreshold",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "policyNonce",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "receipts",
        "type": "tuple[3]",
        "internalType": "struct PayGuardTypes.PolicyReceipt[3]",
        "components": [
          {
            "name": "machineId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "keyFingerprint",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "submissionNonce",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "receiptNonce",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "issuedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "signature",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resumePolicy",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokePolicy",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "stopPolicy",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "MachineRegistered",
    "inputs": [
      {
        "name": "machineId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "keyFingerprint",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "signer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PolicyRegistered",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "policyId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "version",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PolicyResumed",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PolicyRevoked",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PolicyStopped",
    "inputs": [
      {
        "name": "policyCommitment",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "DuplicateMachine",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidBinding",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidReceipt",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidState",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MachineAlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPolicyOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PolicyAlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownMachine",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownPolicy",
    "inputs": []
  }
] as const;

export const PayGuardVaultAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "admin_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "accounting",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PayGuardVault.Accounting",
        "components": [
          {
            "name": "deposited",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "available",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "reserved",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spent",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "withdrawn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "refunded",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deposit",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "beneficiary",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "execute",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "release",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "reservations",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "active",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reserve",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "requestId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "router",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setRouter",
    "inputs": [
      {
        "name": "router_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setSupportedAsset",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "supported",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportedAsset",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "supported",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AssetSupportUpdated",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "supported",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Deposited",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Executed",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "target",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Released",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Reserved",
    "inputs": [
      {
        "name": "requestId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RouterWired",
    "inputs": [
      {
        "name": "router",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyWired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AssetCannotBeDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ConservationViolation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAvailable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAsset",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotRouter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Reentrancy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReservationExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownReservation",
    "inputs": []
  }
] as const;
